package com.creche.crecheapp.exception;

public enum ErrorCodes {
    CHILD_NOT_FOUND(1000),
    CHILD_NOT_VALID(1001),
    CHILD_ALREADY_EXISTS(1002),
    PARENT_NOT_FOUND(1003),
    PARENT_NOT_VALID(1004),
    PARENT_ALREADY_EXISTS(1005),
    CRECHE_NOT_FOUND(1006),
    CRECHE_NOT_VALID(1007),
    CRECHE_ALREADY_EXISTS(1008),
    CRECHE_CHILD_NOT_FOUND(1009),
    CRECHE_CHILD_NOT_VALID(1010),
    CRECHE_CHILD_ALREADY_EXISTS(1011),
    CRECHE_PARENT_NOT_FOUND(1012),
    CRECHE_PARENT_NOT_VALID(1013),
    CRECHE_PARENT_ALREADY_EXISTS(1014),
    CRECHE_STAFF_NOT_FOUND(1015),
    CRECHE_STAFF_NOT_VALID(1016),
    CRECHE_STAFF_ALREADY_EXISTS(1017),
    STAFF_NOT_FOUND(1018),
    STAFF_NOT_VALID(1019),
    STAFF_ALREADY_EXISTS(1020),
    STAFF_CHILD_NOT_FOUND(1021),
    STAFF_CHILD_NOT_VALID(1022),
    STAFF_CHILD_ALREADY_EXISTS(1023),

    // Liste des exception techniaues
    UPDATE_PHOTO_EXCEPTION(14000),
    UNKNOWN_CONTEXT(14001)




    ;

    private int code;

    ErrorCodes(int code) {
        this.code = code;
    }

    public int getCode() {
        return code;
    }
}

